version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    command: sh -c "/wait-for-it.sh db:5432 -- python manage.py migrate && gunicorn --bind 0.0.0.0:8000 backend.wsgi"
    volumes:
      - static:/backend_static
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./gateway/
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80 
